MAX_QUEUE_JOBS = 48
MAX_CLUSTER_NODES = 64

JOB_FEAT_DIM = 27
NODE_FEAT_DIM = 7
CLUSTER_FEAT_DIM = 9
STATE_DIM = (MAX_QUEUE_JOBS * JOB_FEAT_DIM) + (MAX_CLUSTER_NODES * NODE_FEAT_DIM) + CLUSTER_FEAT_DIM

MAX_JOB_GPU = 64.0
MAX_NODE_GPU = 8.0
MAX_TOPOLOGY_SENSITIVITY = 2.0
MAX_CPU_MILLI = 128000.0
MAX_MEM_BYTES = 2048.0 * (1024**3)
MAX_JOB_DURATION = 604800.0
MAX_WAIT_TIME = 604800.0
MAX_TIME_HORIZON = 1209600.0

GAMMA = 0.99
GAE_LAMBDA = 0.95
CLIP_EPS = 0.2
LR = 3e-4
ENTROPY_COEFF = 0.01
VALUE_COEFF = 0.5
PPO_EPOCHS = 4
BATCH_SIZE = 128

DEFAULT_EPISODE_JOBS = 32
DEFAULT_ARRIVAL_SPAN = 0.0
DEFAULT_TRAINING_ITERATIONS = 10
DEFAULT_EPISODES_PER_ITERATION = 10
DEFAULT_EVAL_EPISODES = 20
DEFAULT_WORKLOAD_PRESET = "kueue-lingjun-gang-starvation-cohort"

# When two checkpoints are close on validation JCT, prefer the one that
# preserves fragmentation and topology better instead of always picking the
# absolute minimum JCT snapshot.
CHECKPOINT_JCT_TOLERANCE = 0.03
